org: kaiprince
app: languish
service: translate
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "translate:TranslateText"
            - "comprehend:DetectDominantLanguage"
          Resource:
            - "*"

functions:
  translateWordForWord:
    handler: handler.translateWordForWord
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /
          method: post
    url:
      cors: true
