org: kaiprince
app: languish
service: translate
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "translate:TranslateText"
          Resource:
            - "*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /
          method: post
    url:
      cors:
        allowedOrigins:
          - http://localhost:8000
          - https://languish.kaiprince.xyz
