name: Deploy serverless functions

on:
  push:
    branches:
      - main
    paths:
      - "functions/**"
      - ".github/workflows/serverless.yml"

defaults:
  run:
    working-directory: "functions/translate"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Serverless Deploy
        run: npx serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
