name: Deploy serverless functions

on:
  push:
    branches:
      - main
    paths:
      - "functions/**"

defaults:
  run:
    working-directory: "functions/translate"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - name: Serverless Deploy
        run: npx serverless deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
